version: '3.4'

services:
    db:
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test
        ports:
            - 5432:5432
