version: '3.4'

services:
    db:
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test
        ports:
            - 5432:5432

    collector:
        build:
            context: ./
            dockerfile: ./Dockerfile.collector
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test
            - POSTGRES_HOST=db
        depends_on: ['db']

    frontend:
        volumes: 
            - "./frontend/src:/app/src"

        build:
            context: ./frontend/
            dockerfile: ./Dockerfile.frontend.dev
        environment:
            - REACT_APP_ENVIRONMENT=development
            - CI=true
        ports:
            - 3000:3000